export type AcademicSourceKind =
  | 'Критическое издание'
  | 'Цифровой корпус'
  | 'Музыкальная теория'
  | 'Археомузыкология'
  | 'Учебник для музыкальных вузов'

export interface AcademicSource {
  id: string
  title: string
  authors: string
  year: string
  language: 'RU' | 'EN' | 'DE / EN'
  kind: AcademicSourceKind
  scope: string
  url: string
  access: 'Открытый доступ' | 'Описание / издатель'
}

export type DocumentReviewStatus = 'Готов к карточке' | 'Нужна атрибуция фрагмента'

export interface AdditionalAncientDocument {
  id: string
  title: string
  date: string
  carrier: string
  genre: string
  dagm: string
  status: DocumentReviewStatus
  note: string
  sourceUrl: string
}

export interface ResearchAxis {
  id: string
  title: string
  corpus: string
  conclusion: string
  catalogRule: string
}

const hagelMelodiesUrl = 'https://www.oeaw.ac.at/kal/agm/docum/main.htm'

export const additionalAncientDocuments: AdditionalAncientDocument[] = [
  {
    id: 'pzenon-59533',
    title: 'P.Zenon 59 533',
    date: 'середина III века до н. э.',
    carrier: 'Папирус Зенона',
    genre: 'Фрагмент трагедии (?)',
    dagm: 'DAGM 8',
    status: 'Нужна атрибуция фрагмента',
    note: 'Музыкальная нотация сохранилась фрагментарно; имя автора и пьеса не установлены.',
    sourceUrl: hagelMelodiesUrl,
  },
  {
    id: 'phibeh-231',
    title: 'P.Hibeh 231',
    date: 'III век до н. э.',
    carrier: 'Папирус из Эль-Хибы',
    genre: 'Содержание не установлено',
    dagm: 'DAGM 7',
    status: 'Нужна атрибуция фрагмента',
    note: 'Сохранились нотные знаки, но контекст произведения остаётся неопределённым.',
    sourceUrl: hagelMelodiesUrl,
  },
  {
    id: 'pashmol-89b-31-33',
    title: 'P.Ashm. 89B/31, 33',
    date: 'III—II века до н. э.',
    carrier: 'Папирус Эшмоловского музея',
    genre: '«Ахилл» Софокла Младшего (?)',
    dagm: 'DAGM 5',
    status: 'Нужна атрибуция фрагмента',
    note: 'Связь с драмой Софокла Младшего предположительна и должна сохраняться со знаком вопроса.',
    sourceUrl: hagelMelodiesUrl,
  },
  {
    id: 'pashmol-89b-29-32',
    title: 'P.Ashm. 89B/29–32',
    date: 'III—II века до н. э.',
    carrier: 'Папирус Эшмоловского музея',
    genre: 'Неопределённые фрагменты',
    dagm: 'DAGM 6',
    status: 'Нужна атрибуция фрагмента',
    note: 'Несколько фрагментов с нотацией без надёжного названия произведения.',
    sourceUrl: hagelMelodiesUrl,
  },
  {
    id: 'poslo-1413-1-15',
    title: 'P.Oslo 1413, строки 1–15',
    date: 'I—II века н. э.',
    carrier: 'Папирус Осло',
    genre: 'Драматическая песня',
    dagm: 'DAGM 39',
    status: 'Нужна атрибуция фрагмента',
    note: 'Первый из двух самостоятельных нотированных участков одного папируса.',
    sourceUrl: hagelMelodiesUrl,
  },
  {
    id: 'poslo-1413-16-19',
    title: 'P.Oslo 1413, строки 16–19 «Ô Lêmne»',
    date: 'I—II века н. э.',
    carrier: 'Папирус Осло',
    genre: 'Драматическая песня',
    dagm: 'DAGM 40',
    status: 'Нужна атрибуция фрагмента',
    note: 'Второй нотированный участок P.Oslo 1413 каталогизирован отдельно.',
    sourceUrl: hagelMelodiesUrl,
  },
  {
    id: 'mesomedes-nemesis',
    title: 'Гимн Немезиде',
    date: 'первая половина II века н. э.',
    carrier: 'Рукописная традиция',
    genre: 'Гимн',
    dagm: 'DAGM 28',
    status: 'Готов к карточке',
    note: 'Атрибутирован Месомеду Критскому; следующий очевидный памятник для основного каталога.',
    sourceUrl: hagelMelodiesUrl,
  },
  {
    id: 'pyale-ctybr-4510',
    title: 'P.Yale CtYBR 4510 «Nárkisson»',
    date: 'первая половина II века н. э.',
    carrier: 'Папирус Йельского университета',
    genre: 'Лирические стихи',
    dagm: 'DAGM 41',
    status: 'Нужна атрибуция фрагмента',
    note: 'Фрагмент лирического характера с древнегреческой нотацией.',
    sourceUrl: hagelMelodiesUrl,
  },
  {
    id: 'poxy-2436',
    title: 'P.Oxy. 2436 «Paîs Áreos»',
    date: 'II век н. э.',
    carrier: 'Оксиринхский папирус',
    genre: 'Сатировская драма (?)',
    dagm: 'DAGM 38',
    status: 'Нужна атрибуция фрагмента',
    note: 'Жанровая идентификация как сатировской драмы остаётся предположительной.',
    sourceUrl: hagelMelodiesUrl,
  },
  {
    id: 'pmichigan-2958',
    title: 'P.Michigan 2958 «Ô phíltate»',
    date: 'II век н. э.',
    carrier: 'Мичиганский папирус',
    genre: 'Драматическая песня',
    dagm: 'DAGM 42',
    status: 'Нужна атрибуция фрагмента',
    note: 'Нотированный драматический фрагмент; автор и полное произведение не установлены.',
    sourceUrl: hagelMelodiesUrl,
  },
  {
    id: 'poxy-3704-synaimos',
    title: 'P.Oxy. 3704 «Ho sýnaimos»',
    date: 'II век н. э.',
    carrier: 'Оксиринхский папирус',
    genre: 'Неопределённый фрагмент',
    dagm: 'DAGM 44a',
    status: 'Нужна атрибуция фрагмента',
    note: 'Первый из двух отдельно индексируемых музыкальных фрагментов папируса.',
    sourceUrl: hagelMelodiesUrl,
  },
  {
    id: 'poxy-3704-genetei',
    title: 'P.Oxy. 3704 «Idíoi genétei»',
    date: 'II век н. э.',
    carrier: 'Оксиринхский папирус',
    genre: 'Неопределённый фрагмент',
    dagm: 'DAGM 44b',
    status: 'Нужна атрибуция фрагмента',
    note: 'Второй музыкальный фрагмент того же папируса; хранится как отдельная позиция корпуса.',
    sourceUrl: hagelMelodiesUrl,
  },
  {
    id: 'pmichigan-1250',
    title: 'P.Michigan 1250',
    date: 'I—III века н. э.',
    carrier: 'Мичиганский папирус',
    genre: 'Инструментальный фрагмент',
    dagm: 'DAGM 61',
    status: 'Нужна атрибуция фрагмента',
    note: 'Редкий документ без вокального текста; инструмент и контекст точно не установлены.',
    sourceUrl: hagelMelodiesUrl,
  },
  {
    id: 'pberlin-6870-paian',
    title: 'P.Berlin 6870, строки 1–15',
    date: 'II—III века н. э.',
    carrier: 'Берлинский папирус',
    genre: 'Фрагментированный пеан и инструментальный эпизод',
    dagm: 'DAGM 50s',
    status: 'Нужна атрибуция фрагмента',
    note: 'Сочетает вокальную и инструментальную части; обозначение 50s охватывает группу фрагментов.',
    sourceUrl: hagelMelodiesUrl,
  },
  {
    id: 'pberlin-6870-ajax',
    title: 'P.Berlin 6870, строки 16–19, 23 «Aiax»',
    date: 'II—III века н. э.',
    carrier: 'Берлинский папирус',
    genre: 'Драматический плач о смерти Аякса',
    dagm: 'DAGM 17s',
    status: 'Нужна атрибуция фрагмента',
    note: 'Текст связывает фрагмент с Аяксом, но полная драма и автор не установлены.',
    sourceUrl: hagelMelodiesUrl,
  },
  {
    id: 'pberlin-6870-instrumental',
    title: 'P.Berlin 6870, строки 20–22',
    date: 'II—III века н. э.',
    carrier: 'Берлинский папирус',
    genre: 'Инструментальный фрагмент для авлоса (?)',
    dagm: 'DAGM 52',
    status: 'Нужна атрибуция фрагмента',
    note: 'Связь с авлосом вероятна, но не доказана непосредственно носителем.',
    sourceUrl: hagelMelodiesUrl,
  },
  {
    id: 'poxy-4463',
    title: 'P.Oxy. 4463',
    date: 'II—III века н. э.',
    carrier: 'Оксиринхский папирус',
    genre: 'Драматические фрагменты (?)',
    dagm: 'DAGM 47',
    status: 'Нужна атрибуция фрагмента',
    note: 'Драматическая природа материала предполагается по контексту.',
    sourceUrl: hagelMelodiesUrl,
  },
  {
    id: 'poxy-4464',
    title: 'P.Oxy. 4464',
    date: 'II—III века н. э.',
    carrier: 'Оксиринхский папирус',
    genre: 'Драматический фрагмент',
    dagm: 'DAGM 48',
    status: 'Нужна атрибуция фрагмента',
    note: 'Небольшой нотированный драматический фрагмент без надёжной авторской атрибуции.',
    sourceUrl: hagelMelodiesUrl,
  },
  {
    id: 'poxy-4465',
    title: 'P.Oxy. 4465',
    date: 'II—III века н. э.',
    carrier: 'Оксиринхский папирус',
    genre: 'Драматический фрагмент',
    dagm: 'DAGM 49',
    status: 'Нужна атрибуция фрагмента',
    note: 'Следующая отдельная позиция серии опубликованных оксиринхских нотированных папирусов.',
    sourceUrl: hagelMelodiesUrl,
  },
  {
    id: 'poxy-3161-recto',
    title: 'P.Oxy. 3161 recto',
    date: 'III век н. э.',
    carrier: 'Оксиринхский папирус',
    genre: 'Драматические фрагменты',
    dagm: 'DAGM 53',
    status: 'Нужна атрибуция фрагмента',
    note: 'Лицевая сторона папируса каталогизирована отдельно от оборотной.',
    sourceUrl: hagelMelodiesUrl,
  },
  {
    id: 'poxy-3161-verso',
    title: 'P.Oxy. 3161 verso',
    date: 'III век н. э.',
    carrier: 'Оксиринхский папирус',
    genre: 'Драматические фрагменты',
    dagm: 'DAGM 54',
    status: 'Нужна атрибуция фрагмента',
    note: 'Оборотная сторона содержит другую музыкальную позицию корпуса.',
    sourceUrl: hagelMelodiesUrl,
  },
  {
    id: 'poxy-3705',
    title: 'P.Oxy. 3705',
    date: 'III век н. э.',
    carrier: 'Оксиринхский папирус',
    genre: 'Стих с четырьмя вариантами мелодии',
    dagm: 'DAGM 56',
    status: 'Нужна атрибуция фрагмента',
    note: 'Передаёт четыре альтернативные музыкальные установки; транскрипция остаётся спорной.',
    sourceUrl: hagelMelodiesUrl,
  },
  {
    id: 'poxy-4466',
    title: 'P.Oxy. 4466',
    date: 'III век н. э.',
    carrier: 'Оксиринхский папирус',
    genre: 'Гимнический фрагмент (?)',
    dagm: 'DAGM 57',
    status: 'Нужна атрибуция фрагмента',
    note: 'Гимнический характер возможен, но в академическом указателе отмечен как неуверенный.',
    sourceUrl: hagelMelodiesUrl,
  },
]

export const academicSources: AcademicSource[] = [
  {
    id: 'poehlmann-west-dagm',
    title: 'Documents of Ancient Greek Music',
    authors: 'Egert Pöhlmann, Martin L. West',
    year: '2001',
    language: 'EN',
    kind: 'Критическое издание',
    scope: 'Стандартное критическое собрание древнегреческих музыкальных документов с транскрипциями и комментариями.',
    url: 'https://books.google.com/books/about/Documents_of_Ancient_Greek_Music.html?id=jVud8Fz6wTMC',
    access: 'Описание / издатель',
  },
  {
    id: 'hagel-technical-history',
    title: 'Ancient Greek Music: A New Technical History',
    authors: 'Stefan Hagel',
    year: '2009',
    language: 'EN',
    kind: 'Музыкальная теория',
    scope: 'Техническая история строя, нотации, инструментов и сохранившихся музыкальных документов.',
    url: 'https://www.cambridge.org/core/books/abs/ancient-greek-music/contents/49A4356B9148D58E0D7EEEBAFBE85F28',
    access: 'Описание / издатель',
  },
  {
    id: 'ddagm',
    title: "Database ‘Documents of Ancient Greek Music’ 1.1",
    authors: 'Tosca A. C. Lynch',
    year: '2021',
    language: 'EN',
    kind: 'Цифровой корпус',
    scope: 'Машиночитаемая база всех нот, засвидетельствованных в документах стандартного издания DAGM.',
    url: 'https://www.classics.ox.ac.uk/publication/1193103/hyrax',
    access: 'Открытый доступ',
  },
  {
    id: 'hagel-melodies',
    title: 'Ancient Greek Music: The Melodies',
    authors: 'Stefan Hagel / Austrian Academy of Sciences',
    year: 'обновляемый ресурс',
    language: 'DE / EN',
    kind: 'Цифровой корпус',
    scope: 'Указатель всех опубликованных фрагментов длиннее нескольких разрозненных нот и исследовательские озвучивания.',
    url: hagelMelodiesUrl,
    access: 'Открытый доступ',
  },
  {
    id: 'gibson-hurrian-h6',
    title: 'Rethinking ancient music interpretation through Hurrian Hymn H6: a tablaturization',
    authors: 'Dylan Lawrence Gibson',
    year: '2026',
    language: 'EN',
    kind: 'Археомузыкология',
    scope: 'Критика переноса h.6 в современную западную нотацию и предложение табулатурного представления.',
    url: 'https://academic.oup.com/em/article/53/3/284/8442961',
    access: 'Описание / издатель',
  },
  {
    id: 'uet-vi-3-8991',
    title: 'The Old Babylonian tuning text UET VI/3 8991',
    authors: 'Sam Mirelman, Theo J. H. Krispijn',
    year: '2009',
    language: 'EN',
    kind: 'Музыкальная теория',
    scope: 'Издание и анализ старовавилонской инструкции по циклу настройки струнного инструмента.',
    url: 'https://doi.org/10.1017/S0021088900000735',
    access: 'Описание / издатель',
  },
  {
    id: 'sippar-tablet',
    title: 'A Music Tablet from Sippar(?) BM 65217 + 66616',
    authors: 'Irving L. Finkel, Sam Mirelman',
    year: '2015',
    language: 'EN',
    kind: 'Музыкальная теория',
    scope: 'Исследование месопотамской таблички с музыкально-теоретическим содержанием.',
    url: 'https://www.cambridge.org/core/journals/iraq/article/abs/music-tablet-from-sippar-bm-65217-66616/52216F3358DA6DC445D0507BC5075ECC',
    access: 'Описание / издатель',
  },
  {
    id: 'manniche-egypt',
    title: 'Music, Pharaonic Egypt',
    authors: 'Lise Manniche',
    year: '2012',
    language: 'EN',
    kind: 'Археомузыкология',
    scope: 'Обзор инструментов, изображений и текстов при отсутствии древнеегипетской нотной записи.',
    url: 'https://onlinelibrary.wiley.com/doi/abs/10.1002/9781444338386.wbeah15288',
    access: 'Описание / издатель',
  },
  {
    id: 'ucl-egypt-written',
    title: 'Written sources for ancient Egyptian music',
    authors: 'UCL Digital Egypt for Universities',
    year: 'цифровой ресурс',
    language: 'EN',
    kind: 'Цифровой корпус',
    scope: 'Путеводитель по письменным свидетельствам, песенным текстам и изображениям музыкантов Древнего Египта.',
    url: 'https://www.ucl.ac.uk/museums-static/digitalegypt/furniture/musicwritten.html',
    access: 'Открытый доступ',
  },
  {
    id: 'cosgrove-oxy-hymn',
    title: 'An Ancient Christian Hymn with Musical Notation: Papyrus Oxyrhynchus 1786',
    authors: 'Charles H. Cosgrove',
    year: '2011',
    language: 'EN',
    kind: 'Критическое издание',
    scope: 'Монографическое исследование текста, нотации и исторического контекста P.Oxy. 1786.',
    url: 'https://www.mohrsiebeck.com/buch/an-ancient-christian-hymn-with-musical-notation-9783161517679/',
    access: 'Описание / издатель',
  },
  {
    id: 'oxford-programme',
    title: 'Ancient Music at Oxford: Programme Notes',
    authors: 'University of Oxford',
    year: 'цифровой ресурс',
    language: 'EN',
    kind: 'Археомузыкология',
    scope: 'Пояснения к реконструкциям Orestes, дельфийских гимнов, Месомеда и P.Oxy. 1786.',
    url: 'https://ancientmusicoxford.site.ox.ac.uk/programme-notes',
    access: 'Открытый доступ',
  },
  {
    id: 'mts-moscow',
    title: 'Музыкально-теоретические системы',
    authors: 'Ю. Н. Холопов, Л. В. Кириллина, Т. С. Кюрегян и др.',
    year: '2006',
    language: 'RU',
    kind: 'Учебник для музыкальных вузов',
    scope: 'Вузовский курс для музыковедов и композиторов; древнегреческая теория открывает историческую часть учебника.',
    url: 'https://www.mosconsv.ru/ru/publication.aspx?id=122532',
    access: 'Описание / издатель',
  },
  {
    id: 'greek-music-writers',
    title: 'Музыкальные писатели античной Греции',
    authors: 'переводы и комментарии В. Г. Цыпина',
    year: '2019',
    language: 'RU',
    kind: 'Критическое издание',
    scope: 'Русские переводы Клеонида, Алипия, Анонимов Беллермана, Бакхия, Гауденция, Никомаха, Теона и Евклида.',
    url: 'https://www.mosconsv.ru/ru/publication/161828',
    access: 'Описание / издатель',
  },
  {
    id: 'losev-aesthetics',
    title: 'Античная музыкальная эстетика',
    authors: 'А. Ф. Лосев',
    year: '1960',
    language: 'RU',
    kind: 'Музыкальная теория',
    scope: 'Источниковедческий обзор античных представлений о музыке, числе, этосе и гармонии.',
    url: 'https://rusneb.ru/catalog/002178_000020_BGUNB-BEL%7C%7C%7CBIBL%7C%7C%7C0000556875/',
    access: 'Открытый доступ',
  },
  {
    id: 'lynch-imperial-melodies',
    title: 'Unlocking the Riddles of Imperial Greek Melodies',
    authors: 'Tosca A. C. Lynch',
    year: '2024',
    language: 'EN',
    kind: 'Музыкальная теория',
    scope: 'Анализ развития гармонической системы и нотации императорского периода на данных dDAGM.',
    url: 'https://brill.com/view/journals/grms/12/1/article-p70_4.xml?language=en',
    access: 'Открытый доступ',
  },
]

export const researchAxes: ResearchAxis[] = [
  {
    id: 'near-east',
    title: 'Месопотамия и Угарит',
    corpus: 'Клинописные песенные тексты, названия струн, интервальные термины, инструкции настройки и хурритские таблички.',
    conclusion: 'Теория настройки документирована лучше, чем конкретные мелодии. Для h.6 существуют конкурирующие дешифровки; единственной окончательной версии нет.',
    catalogRule: 'Каждая запись должна разделять древние знаки, научную транскрипцию и современное звуковое решение.',
  },
  {
    id: 'egypt',
    title: 'Древний Египет',
    corpus: 'Песенные тексты, изображения ансамблей, инструменты и административные свидетельства о музыкантах.',
    conclusion: 'Древнеегипетская нотная запись не сохранилась. Современная аудиозапись может иллюстрировать текст или тембр реконструированного инструмента, но не исходную мелодию.',
    catalogRule: 'Египетские карточки помечаются как современные интерпретации; наличие текста не считается наличием нот.',
  },
  {
    id: 'greek-roman',
    title: 'Греция и римский период',
    corpus: 'Буквенная вокальная и инструментальная нотация на камне, папирусе и в рукописной передаче; трактаты о гармонике и ритмике.',
    conclusion: 'Это наиболее прямой нотированный древний корпус, однако темп, инструментовка, строй и заполнение лакун часто остаются решениями исполнителя.',
    catalogRule: 'Карточка получает номер DAGM, точный носитель, меру фрагментарности и ссылку на критическое издание.',
  },
  {
    id: 'higher-education',
    title: 'Теория для музыкальных вузов',
    corpus: 'Русские вузовские учебники сопоставляются с критическими изданиями, античными трактатами и современной англоязычной археомузыкологией.',
    conclusion: 'Учебник объясняет систему понятий, но не заменяет проверку чтения конкретного папируса или надписи по корпусу DAGM.',
    catalogRule: 'Общие определения берутся из учебной литературы, а данные карточки — из издания памятника и профильной статьи.',
  },
]

export const researchUpdatedAt = '19 сентября 2026'
