export type AncientEvidence = 'notation' | 'text'

export interface AncientWork {
  id: string
  title: string
  originalTitle?: string
  date: string
  author: string
  evidence: AncientEvidence
  sourceTitle: string
  sourceUrl: string
}

export interface AncientTradition {
  id: string
  name: string
  place: string
  range: string
  note: string
  works: AncientWork[]
}

export const evidenceLabels: Record<AncientEvidence, string> = {
  notation: 'Сохранилась нотация',
  text: 'Текст / мелодия утрачена',
}

export const ancientTraditions: AncientTradition[] = [
  {
    id: 'sumer-akkad',
    name: 'Шумер и Аккад',
    place: 'Месопотамия',
    range: 'ок. 2600—1750 до н. э.',
    note: 'Древнейшие названные гимны и песни дошли как клинописные тексты. Их исходные мелодии не записаны.',
    works: [
      {
        id: 'kesh-temple-hymn',
        title: 'Гимн храму Кеша',
        originalTitle: 'Kesh Temple Hymn',
        date: 'ок. 2600—2500 до н. э.',
        author: 'Неизвестный автор',
        evidence: 'text',
        sourceTitle: 'CDLI: Kesh Temple Hymn',
        sourceUrl: 'https://cdli.earth/cdli-tablet/190',
      },
      {
        id: 'temple-hymns',
        title: 'Собрание храмовых гимнов',
        originalTitle: 'Temple Hymns',
        date: 'ок. 2300 до н. э.',
        author: 'Энхедуанна (составитель и автор)',
        evidence: 'text',
        sourceTitle: 'Penn Museum: Enheduanna',
        sourceUrl: 'https://www.penn.museum/sites/expedition/goddesses-mothers-rulers/',
      },
      {
        id: 'exaltation-inanna',
        title: 'Возвышение Инанны',
        originalTitle: 'Nin-me-šara',
        date: 'ок. 2300 до н. э.',
        author: 'Энхедуанна',
        evidence: 'text',
        sourceTitle: 'Penn Museum: The Exaltation of Inanna',
        sourceUrl: 'https://www.penn.museum/sites/expedition/goddesses-mothers-rulers/',
      },
      {
        id: 'hymn-inanna',
        title: 'Гимн Инанне',
        originalTitle: 'A Hymn to Inanna',
        date: 'ок. 2300 до н. э.',
        author: 'Энхедуанна',
        evidence: 'text',
        sourceTitle: 'Penn Museum: Enheduanna',
        sourceUrl: 'https://www.penn.museum/sites/expedition/goddesses-mothers-rulers/',
      },
      {
        id: 'inanna-ebih',
        title: 'Инанна и Эбих',
        originalTitle: 'Inanna and Ebih',
        date: 'ок. 2300 до н. э.',
        author: 'Приписывается Энхедуанне',
        evidence: 'text',
        sourceTitle: 'Penn Museum: Inanna and Ebih',
        sourceUrl: 'https://www.penn.museum/sites/expedition/goddesses-mothers-rulers/',
      },
      {
        id: 'shulgi-a',
        title: 'Гимн Шульги A',
        originalTitle: 'Shulgi A',
        date: 'ок. 2094—2047 до н. э.',
        author: 'Неизвестный придворный автор',
        evidence: 'text',
        sourceTitle: 'CDLI: каталог шумерской литературы',
        sourceUrl: 'https://www.cdli.earth/inscriptions/2234629',
      },
      {
        id: 'lipit-ishtar-b',
        title: 'Гимн Липит-Иштару B',
        originalTitle: 'Lipit-Ištar B',
        date: 'ок. 1934—1924 до н. э.',
        author: 'Неизвестный автор',
        evidence: 'text',
        sourceTitle: 'CDLI: Lipit-Ištar B',
        sourceUrl: 'https://cdli.earth/P268965',
      },
    ],
  },
  {
    id: 'egypt',
    name: 'Древний Египет',
    place: 'Долина Нила',
    range: 'ок. 1700—305 до н. э.',
    note: 'Названия и слова сохранились на папирусах и стенах гробниц, но египтяне не оставили нотной записи этих мелодий.',
    works: [
      {
        id: 'sobek-hymns',
        title: 'Цикл гимнов Собеку',
        originalTitle: 'Ramesseum Hymns to Sobek',
        date: 'ок. 1700 до н. э.',
        author: 'Неизвестный автор',
        evidence: 'text',
        sourceTitle: 'British Museum: Papyrus Ramesseum 6',
        sourceUrl: 'https://www.britishmuseum.org/collection/object/Y_EA10759-3',
      },
      {
        id: 'great-hymn-aten',
        title: 'Великий гимн Атону',
        originalTitle: 'Great Hymn to the Aten',
        date: 'ок. 1350 до н. э.',
        author: 'Вероятно Эхнатон',
        evidence: 'text',
        sourceTitle: 'The Met: Hymn to the Aten',
        sourceUrl: 'https://www.metmuseum.org/art/collection/search/544056',
      },
      {
        id: 'harpist-song-intef',
        title: 'Песнь арфиста из дома Интефа',
        originalTitle: "Harpist's Song from the Mansion of Intef",
        date: 'ок. 1295—1186 до н. э.',
        author: 'Неизвестный автор',
        evidence: 'text',
        sourceTitle: 'British Museum: Papyrus Harris 500',
        sourceUrl: 'https://www.britishmuseum.org/collection/object/Y_EA10060',
      },
      {
        id: 'harris-love-songs',
        title: 'Любовные песни папируса Харриса 500',
        originalTitle: 'Love Songs of Papyrus Harris 500',
        date: 'ок. 1295—1186 до н. э.',
        author: 'Неизвестные авторы',
        evidence: 'text',
        sourceTitle: 'British Museum: Papyrus Harris 500',
        sourceUrl: 'https://www.britishmuseum.org/collection/object/Y_EA10060',
      },
      {
        id: 're-horakhty-hymn',
        title: 'Гимн Ра-Хорахти',
        originalTitle: 'Hymn to Re-Horakhty',
        date: 'ок. 1069—664 до н. э.',
        author: 'Неизвестный автор',
        evidence: 'text',
        sourceTitle: 'British Museum: Papyrus EA10474',
        sourceUrl: 'https://www.britishmuseum.org/collection/object/Y_EA10474-7',
      },
      {
        id: 'iah-hymn',
        title: 'Гимн Иаху, богу Луны',
        originalTitle: 'Hymn to Iah',
        date: 'ок. 1069—664 до н. э.',
        author: 'Неизвестный автор',
        evidence: 'text',
        sourceTitle: 'British Museum: Papyrus EA10474',
        sourceUrl: 'https://www.britishmuseum.org/collection/object/Y_EA10474-7',
      },
      {
        id: 'isis-nephthys-songs',
        title: 'Песни Исиды и Нефтиды',
        originalTitle: 'Songs of Isis and Nephthys',
        date: '305 до н. э.',
        author: 'Неизвестный автор',
        evidence: 'text',
        sourceTitle: 'British Museum: Bremner-Rhind Papyrus',
        sourceUrl: 'https://www.britishmuseum.org/collection/object/Y_EA10188-1',
      },
    ],
  },
  {
    id: 'hurrian-ugarit',
    name: 'Хурриты и Угарит',
    place: 'Современная Сирия',
    range: 'ок. 1400 до н. э.',
    note: 'Табличка h.6 — древнейшая почти полностью сохранившаяся песня с текстом и системой музыкальных указаний.',
    works: [
      {
        id: 'hurrian-hymn-6',
        title: 'Хурритский гимн Никкаль h.6',
        originalTitle: 'Hurrian Song h.6',
        date: 'ок. 1400 до н. э.',
        author: 'Неизвестный хурритский автор',
        evidence: 'notation',
        sourceTitle: 'National Museum of Damascus: tablet h.6',
        sourceUrl: 'https://virtual-museum-syria.org/damascus/56-tablet-musical-staff/',
      },
      {
        id: 'hurrian-fragments',
        title: 'Хурритские песни h.1—h.5 и h.7—h.29',
        originalTitle: 'Hurrian Songs, fragmentary tablets',
        date: 'ок. 1400 до н. э.',
        author: 'Неизвестные хурритские авторы',
        evidence: 'notation',
        sourceTitle: 'Austrian Academy of Sciences: Music of Ancient Near East',
        sourceUrl: 'https://www.oeaw.ac.at/kal/mane/',
      },
    ],
  },
  {
    id: 'assyrian-babylonian',
    name: 'Ассирия и Вавилония',
    place: 'Северная Месопотамия',
    range: 'ок. 721—612 до н. э.',
    note: 'Новоассирийские таблички сохраняют названия и слова царских и храмовых гимнов. Автором в карточке считается поэт, а не правитель, которому посвящён текст.',
    works: [
      {
        id: 'sargon-nanaya',
        title: 'Гимн Нанайе Саргона II',
        originalTitle: 'Nanaya Hymn of Sargon II',
        date: 'ок. 721—705 до н. э.',
        author: 'Неизвестный придворный автор',
        evidence: 'text',
        sourceTitle: 'ORACC: State Archives of Assyria 3',
        sourceUrl: 'https://oracc.museum.upenn.edu/saao/saa03/corpus',
      },
      {
        id: 'ashurbanipal-ashur',
        title: 'Гимн Ашшурбанипала Ашшуру',
        originalTitle: "Assurbanipal's Hymn to Aššur",
        date: 'ок. 668—627 до н. э.',
        author: 'Неизвестный придворный автор',
        evidence: 'text',
        sourceTitle: 'ORACC: State Archives of Assyria 3',
        sourceUrl: 'https://oracc.museum.upenn.edu/saao/saa03/corpus',
      },
      {
        id: 'ashurbanipal-marduk',
        title: 'Акростихический гимн Мардуку и Царпаниту',
        originalTitle: "Assurbanipal's Acrostic Hymn to Marduk and Zarpanitu",
        date: 'ок. 668—627 до н. э.',
        author: 'Неизвестный придворный автор',
        evidence: 'text',
        sourceTitle: 'ORACC: State Archives of Assyria 3',
        sourceUrl: 'https://oracc.museum.upenn.edu/saao/saa03/corpus',
      },
      {
        id: 'ashurbanipal-ishtars',
        title: 'Гимн Иштар Ниневии и Арбелы',
        originalTitle: "Assurbanipal's Hymn to the Ištars of Nineveh and Arbela",
        date: 'ок. 668—627 до н. э.',
        author: 'Неизвестный придворный автор',
        evidence: 'text',
        sourceTitle: 'ORACC: State Archives of Assyria 3',
        sourceUrl: 'https://oracc.museum.upenn.edu/saao/saa03/corpus',
      },
      {
        id: 'ashurbanipal-nanaya',
        title: 'Гимн Нанайе Ашшурбанипала',
        originalTitle: 'Nanaya Hymn of Assurbanipal',
        date: 'ок. 668—627 до н. э.',
        author: 'Неизвестный придворный автор',
        evidence: 'text',
        sourceTitle: 'ORACC: State Archives of Assyria 3',
        sourceUrl: 'https://oracc.museum.upenn.edu/saao/saa03/corpus',
      },
      {
        id: 'ashurbanipal-tashmetu-nabu',
        title: 'Гимн Ташмету и Набу',
        originalTitle: "Assurbanipal's Hymn to Tašmetu and Nabû",
        date: 'ок. 668—627 до н. э.',
        author: 'Неизвестный придворный автор',
        evidence: 'text',
        sourceTitle: 'ORACC: State Archives of Assyria 3',
        sourceUrl: 'https://oracc.museum.upenn.edu/saao/saa03/corpus',
      },
      {
        id: 'ashurbanipal-coronation',
        title: 'Коронационный гимн Ашшурбанипала',
        originalTitle: "Assurbanipal's Coronation Hymn",
        date: 'ок. 668 до н. э.',
        author: 'Неизвестный придворный автор',
        evidence: 'text',
        sourceTitle: 'ORACC: State Archives of Assyria 3',
        sourceUrl: 'https://oracc.museum.upenn.edu/saao/saa03/corpus',
      },
    ],
  },
  {
    id: 'greece-rome',
    name: 'Древняя Греция и Рим',
    place: 'Средиземноморье',
    range: '408 до н. э.—IV век н. э.',
    note: 'Здесь появляются памятники, по которым возможно более уверенно восстановить мелодический контур и ритм.',
    works: [
      {
        id: 'orestes-stasimon',
        title: 'Стасим из «Ореста»',
        originalTitle: 'Orestes, stasimon',
        date: 'текст 408 до н. э.; ноты ок. 200 до н. э.',
        author: 'Еврипид (текст); музыка неизвестного автора',
        evidence: 'notation',
        sourceTitle: 'Cambridge: Euripides Orestes musical papyrus',
        sourceUrl: 'https://www.cambridge.org/core/journals/journal-of-hellenic-studies/volume/journal-jhs-volume-76/B9AC44B4A22A2105D17F15DF301EB300',
      },
      {
        id: 'first-delphic-hymn',
        title: 'Первый Дельфийский гимн Аполлону',
        originalTitle: 'First Delphic Hymn to Apollo',
        date: '128 до н. э.',
        author: 'Афиней, сын Афинея',
        evidence: 'notation',
        sourceTitle: 'Archaeological Museum of Delphi: Hymns to Apollo',
        sourceUrl: 'https://delphi.culture.gr/museum/selected-exhibits/',
      },
      {
        id: 'second-delphic-hymn',
        title: 'Второй Дельфийский гимн Аполлону',
        originalTitle: 'Second Delphic Hymn to Apollo',
        date: '128 до н. э.',
        author: 'Лимений, сын Фоина',
        evidence: 'notation',
        sourceTitle: 'Archaeological Museum of Delphi: Hymns to Apollo',
        sourceUrl: 'https://delphi.culture.gr/museum/selected-exhibits/',
      },
      {
        id: 'seikilos-song',
        title: 'Песня со стелы Сейкила',
        originalTitle: 'Song of Seikilos',
        date: 'ок. 100—200 н. э.',
        author: 'Неизвестный автор; возможно Сейкил',
        evidence: 'notation',
        sourceTitle: 'National Museum of Denmark: Seikilos stele',
        sourceUrl: 'https://natmus.dk/historisk-viden/verden/middelhavslandene/graekenland/de-foerste-noder/',
      },
      {
        id: 'mesomedes-muse',
        title: 'Гимн Музе',
        originalTitle: 'Hymn to the Muse',
        date: 'II век н. э.',
        author: 'Месомед Критский',
        evidence: 'notation',
        sourceTitle: 'University of Oxford: music of Mesomedes',
        sourceUrl: 'https://www.sjc.ox.ac.uk/discover/events/ancient-greek-choir-workshop/',
      },
      {
        id: 'mesomedes-sun',
        title: 'Гимн Солнцу',
        originalTitle: 'Hymn to the Sun',
        date: 'II век н. э.',
        author: 'Месомед Критский',
        evidence: 'notation',
        sourceTitle: 'University of Oxford: music of Mesomedes',
        sourceUrl: 'https://www.sjc.ox.ac.uk/discover/events/ancient-greek-choir-workshop/',
      },
      {
        id: 'mesomedes-calliope-apollo',
        title: 'Гимн Каллиопе и Аполлону',
        originalTitle: 'Hymn to Calliope and Apollo',
        date: 'II век н. э.',
        author: 'Месомед Критский',
        evidence: 'notation',
        sourceTitle: 'University of Oxford: music of Mesomedes',
        sourceUrl: 'https://www.sjc.ox.ac.uk/discover/events/ancient-greek-choir-workshop/',
      },
      {
        id: 'oxyrhynchus-hymn',
        title: 'Оксиринхский христианский гимн',
        originalTitle: 'P.Oxy. 1786 Trinitarian Hymn',
        date: 'конец III—начало IV века н. э.',
        author: 'Неизвестный автор',
        evidence: 'notation',
        sourceTitle: 'Oxford Ancient Music: programme notes',
        sourceUrl: 'https://ancientmusicoxford.site.ox.ac.uk/programme-notes',
      },
    ],
  },
]

export const ancientWorkCount = ancientTraditions.reduce((total, tradition) => total + tradition.works.length, 0)
export const notatedWorkCount = ancientTraditions.reduce(
  (total, tradition) => total + tradition.works.filter((work) => work.evidence === 'notation').length,
  0,
)
