# Generated by Django 5.2.17 on 2026-08-08 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_token_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevokedTokenChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain_id', models.UUIDField(unique=True)),
                ('reason', models.CharField(choices=[('logout', 'Logout'), ('reuse', 'Reuse')], max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revoked_chains', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'revoked_token_chains',
                'indexes': [models.Index(fields=['expires_at'], name='revoked_tok_expires_248383_idx')],
            },
        ),
    ]
